<?php
$lang['CONTENT_DESCRIPTION'] = "Free multiplayers management game where you play the manager of a Formula 1 team. Lead your drivers and their cars to victory against hundreds of players from around the world.";
$lang['CONTENT_KEYWORDS'] = "F1, Formula One Manager, Formula 1, Formule 1, Formula 1 Game, Jeu Formule 1, Jeu, Game, F1 Manager, FOM, Free Game, Formula One Game, Jeu Gratuit, Online, Web, Multijoueurs, Multiplayers, Course, Simulation, Course F1, Jeu management, Racing, Racing Game, Championnat";

$lang['BIENVENUE_SUR_FOM'] = "Welcome to Formula One Manager !";
$lang['ACCUEIL'] = "Home";
$lang['INSCRIPTION'] = "Register";
$lang['NEWS'] = "News";
$lang['FORUMS'] = "Forums";
$lang['DOCUMENTATION'] = "Documentation";
$lang['CONNEXION'] = "Log In";
$lang['DECONNEXION'] = "Log Out";
$lang['CONNEXION_AUTO'] = "Automatic";
$lang['PAS_INSCRIT'] = "Not registered yet ?";
$lang['COMMUNAUTE'] = "Community";
$lang['STAFF'] = "Staff";
$lang['SUPPORT'] = "Support";
$lang['MES_DONNEES'] = "My data";
$lang['PARTENAIRES'] = "Partners";
$lang['INSCRIVEZ_VOUS_GRATUITEMENT'] = "Register for free";
$lang['CONNECTEZ_VOUS'] = "Log In";
$lang['PRESENTATION_DE_FOM'] = "Présentation de Formula One Manager";
$lang['ACCUEIL_FOM'] = "Home";
$lang['PILOTES'] = "Drivers";
$lang['MEMBRES'] = "Members";

$lang['TITRE'] = "Formula One Manager - Free F1 Management Game";

$lang['PRESENTATION_FOM'] = "<p>Welcome to Formula One Manager, the first F1 management game <strong>totally free</strong> and always up-to-date with the latest innovations from the world of F1.</p>
<p>Unlike other games of its type, Formula One Manager is free in its entirety. No function or enhancement can be won simply by giving money. This will allow you to play together with the same means to succeed!</p>
<p>To register, click <a href=\"/inscription/\">here</a>! With a few clicks you can begin to play, create your clan, manage your drivers, your researchers and manage your expenses (virtual, of course!), and many more.</p>
<p>The Formula One Manager team wish you a good game. :-)</p>";

$lang['LISTE_DERNIERES_NEWS'] = "Latest news ";
$lang['LOGIN'] = "Log In";

$lang['COMMENTER_CETTE_NEWS'] = "Commenter cette news";
$lang['COMMENTAIRE'] = "commentaire";
$lang['COMMENTAIRES'] = "commentaires";
$lang['NEWS_ECRITE_PAR'] = "Written by";

$lang['PILOTE'] = "Driver";
$lang['GARAGE']	= "Cars";
$lang['CIRCUIT'] = "Race track";
$lang['FINANCES'] = "Finances";
$lang['STRUCTURES'] = "Structures";
$lang['MON_CLAN'] = "My Clan";
$lang['CALENDRIER'] = "Schedule";
$lang['CLASSEMENTS'] = "Ranking";
$lang['HALL_OF_FAME'] = "Hall of Fame";
$lang['MON_COMPTE'] = "My account";

$lang['A_DISPOSITION'] = "Available";
$lang['INFORMATIONS'] = "Informations";
$lang['CLASSEMENT'] = "Ranking";
$lang['SEANCE'] = "Session";
$lang['FIN_SEANCE_DANS'] = "Session end in";
$lang['COURSE_DANS'] = "Race in";
$lang['LA_COURSE'] = "The Race";

$lang['LISTE_PAYS'] = 	
					"<option value=\"fr\"   SELECTED  >France</option>" .
					"<option value=\"uk\" >United-Kingdom</option>" .
					"<option value=\"de\" >Germany</option>" .
					"<option value=\"be\" >Belgium</option>" .
					"<option value=\"it\" >Italia</option>" .
					"<option value=\"es\" >Spain</option>" .
					"<option value=\"us\" >United States of America</option>" .
					"<option disabled>-----------------------</option>" .
					"<option value=\"af\" >Afghanistan</option>" .
                    "<option value=\"al\" >Albanie</option>" .
                    "<option value=\"dz\" >Algérie</option>" .
					"<option value=\"de\" >Allemagne</option>" .
                    "<option value=\"ad\" >Andorre</option>" .
                    "<option value=\"ao\" >Angola</option>" .
                    "<option value=\"ai\" >Anguilla</option>" .
                    "<option value=\"aq\" >Antarctique</option>" .
                    "<option value=\"ar\" >Argentine</option>" .
                    "<option value=\"am\" >Arménie</option>" .
                    "<option value=\"aw\" >Aruba</option>" .
                    "<option value=\"au\" >Australie</option>" .
                    "<option value=\"at\" >Autriche</option>" .
                    "<option value=\"az\" >Azerbaïdjan</option>" .
                    "<option value=\"bs\" >Bahamas</option>" .
                    "<option value=\"bh\" >Bahreïn</option>" .
                    "<option value=\"bd\" >Bangladesh</option>" .
                    "<option value=\"bb\" >Barbade</option>" .
                    "<option value=\"by\" >Biélorussie</option>" .
                    "<option value=\"be\" >Belgique</option>" .
                    "<option value=\"bz\" >Belize</option>" .
                    "<option value=\"bj\" >Bénin</option>" .
                    "<option value=\"bm\" >Bermudes</option>" .
                    "<option value=\"bt\" >Bhoutan</option>" .
                    "<option value=\"bo\" >Bolivie</option>" .
                    "<option value=\"ba\" >Bosnie-Herzégovine</option>" .
                    "<option value=\"bw\" >Botswana</option>" .
                    "<option value=\"br\" >Brésil</option>" .
                    "<option value=\"bn\" >Brunei</option>" .
                    "<option value=\"bg\" >Bulgarie</option>" .
                    "<option value=\"bi\" >Burundi</option>" .
                    "<option value=\"kh\" >Cambodge</option>" .
                    "<option value=\"cm\" >Cameroun</option>" .
                    "<option value=\"ca\" >Canada</option>" .
                    "<option value=\"cv\" >Cap Vert</option>" .
                    "<option value=\"cl\" >Chili</option>" .
                    "<option value=\"cn\" >Chine</option>" .
                    "<option value=\"co\" >Colombie</option>" .
                    "<option value=\"km\" >Comores</option>" .
                    "<option value=\"cr\" >Costa Rica</option>" .
                    "<option value=\"hr\" >Croatie</option>" .
                    "<option value=\"cu\" >Cuba</option>" .
                    "<option value=\"cy\" >Chypre</option>" .
                    "<option value=\"dk\" >Danemark</option>" .
                    "<option value=\"dj\" >Djibouti</option>" .
                    "<option value=\"dm\" >Dominique</option>" .
                    "<option value=\"ec\" >Équateur</option>" .
                    "<option value=\"eg\" >Égypte</option>" .
                    "<option value=\"er\" >Érythrée</option>" .
					"<option value=\"es\" >Espagne</option>" .
                    "<option value=\"ee\" >Estonie</option>" .
					"<option value=\"us\" >Etats-Unis d'Amérique</option>" .
                    "<option value=\"et\" >Éthiopie</option>" .
                    "<option value=\"fk\" >Îles Malouines</option>" .
                    "<option value=\"fo\" >Îles Féroé</option>" .
                    "<option value=\"fj\" >Fidji</option>" .
                    "<option value=\"fi\" >Finlande</option>" .
                    "<option value=\"fr\" >France</option>" .
                    "<option value=\"gf\" >Guyane française</option>" .
                    "<option value=\"pf\" >Polynésie française</option>" .
                    "<option value=\"ga\" >Gabon</option>" .
                    "<option value=\"gm\" >Gambie</option>" .
                    "<option value=\"ge\" >Géorgie</option>" .
                    "<option value=\"gh\" >Ghana</option>" .
                    "<option value=\"gi\" >Gibraltar</option>" .
                    "<option value=\"gr\" >Grèce</option>" .
                    "<option value=\"gl\" >Groenland</option>" .
                    "<option value=\"gd\" >Grenade</option>" .
                    "<option value=\"gp\" >Guadeloupe</option>" .
                    "<option value=\"gu\" >Guam</option>" .
                    "<option value=\"gt\" >Guatemala</option>" .
                    "<option value=\"gn\" >Guinée</option>" .
                    "<option value=\"ht\" >Haïti</option>" .
                    "<option value=\"hn\" >Honduras</option>" .
                    "<option value=\"hu\" >Hongrie</option>" .
                    "<option value=\"is\" >Islande</option>" .
                    "<option value=\"in\" >Inde</option>" .
                    "<option value=\"id\" >Indonésie</option>" .
                    "<option value=\"ir\" >Iran</option>" .
                    "<option value=\"iq\" >Iraq</option>" .
                    "<option value=\"ie\" >Irlande</option>" .
                    "<option value=\"il\" >Israël</option>" .
                    "<option value=\"it\" >Italie</option>" .
                    "<option value=\"ci\" >Côte d'Ivoire</option>" .
                    "<option value=\"jm\" >Jamaïque</option>" .
                    "<option value=\"jp\" >Japon</option>" .
                    "<option value=\"jo\" >Jordanie</option>" .
                    "<option value=\"kz\" >Kazakhstan</option>" .
                    "<option value=\"ke\" >Kenya</option>" .
                    "<option value=\"ki\" >Kiribati</option>" .
                    "<option value=\"kw\" >Koweït</option>" .
                    "<option value=\"kg\" >Kirghizstan</option>" .
                    "<option value=\"la\" >Laos</option>" .
                    "<option value=\"lv\" >Lettonie</option>" .
                    "<option value=\"lb\" >Liban</option>" .
                    "<option value=\"ls\" >Lesotho</option>" .
                    "<option value=\"lr\" >Libéria</option>" .
                    "<option value=\"ly\" >Libye</option>" .
                    "<option value=\"li\" >Liechtenstein</option>" .
                    "<option value=\"lt\" >Lituanie</option>" .
                    "<option value=\"lu\" >Luxembourg</option>" .
                    "<option value=\"mo\" >Macao</option>" .
                    "<option value=\"mk\" >Macédoine</option>" .
                    "<option value=\"mg\" >Madagascar</option>" .
                    "<option value=\"mw\" >Malawi</option>" .
                    "<option value=\"my\" >Malaisie</option>" .
                    "<option value=\"mv\" >Maldives</option>" .
                    "<option value=\"ml\" >Mali</option>" .
                    "<option value=\"mt\" >Malte</option>" .
                    "<option value=\"mq\" >Martinique</option>" .
                    "<option value=\"mr\" >Mauritanie</option>" .
                    "<option value=\"mu\" >Île Maurice</option>" .
                    "<option value=\"yt\" >Mayotte</option>" .
                    "<option value=\"mx\" >Mexique</option>" .
                    "<option value=\"md\" >Moldavie</option>" .
                    "<option value=\"mc\" >Monaco</option>" .
                    "<option value=\"mn\" >Mongolie</option>" .
                    "<option value=\"ms\" >Montserrat</option>" .
                    "<option value=\"ma\" >Maroc</option>" .
                    "<option value=\"mz\" >Mozambique</option>" .
                    "<option value=\"mm\" >Myanmar</option>" .
                    "<option value=\"na\" >Namibie</option>" .
                    "<option value=\"nr\" >Nauru</option>" .
                    "<option value=\"np\" >Népal</option>" .
                    "<option value=\"nl\" >Pays-Bas</option>" .
                    "<option value=\"nc\" >Nouvelle-Calédonie</option>" .
                    "<option value=\"nz\" >Nouvelle-Zélande</option>" .
                    "<option value=\"ni\" >Nicaragua</option>" .
                    "<option value=\"ne\" >Niger</option>" .
                    "<option value=\"ng\" >Nigeria</option>" .
                    "<option value=\"nu\" >Nioué</option>" .
                    "<option value=\"kp\" >Corée du Nord</option>" .
                    "<option value=\"no\" >Norvège</option>" .
                    "<option value=\"om\" >Oman</option>" .
                    "<option value=\"pk\" >Pakistan</option>" .
                    "<option value=\"pw\" >Palau</option>" .
                    "<option value=\"pa\" >Panama</option>" .
                    "<option value=\"py\" >Paraguay</option>" .
                    "<option value=\"pe\" >Pérou</option>" .
                    "<option value=\"ph\" >Philippines</option>" .
                    "<option value=\"pl\" >Pologne</option>" .
                    "<option value=\"pt\" >Portugal</option>" .
                    "<option value=\"pr\" >Porto Rico</option>" .
                    "<option value=\"qa\" >Qatar</option>" .
					"<option value=\"cz\" >République tchèque</option>" .
                    "<option value=\"cd\" >Rép. dém. du Congo</option>" .
                    "<option value=\"re\" >Réunion</option>" .
                    "<option value=\"ro\" >Roumanie</option>" .
                    "<option value=\"ru\" >Russie</option>" .
                    "<option value=\"rw\" >Rwanda</option>" .
                    "<option value=\"ws\" >Samoa</option>" .
                    "<option value=\"sm\" >Saint-Marin</option>" .
                    "<option value=\"sn\" >Sénégal</option>" .
                    "<option value=\"sc\" >Seychelles</option>" .
                    "<option value=\"sl\" >Sierra Leone</option>" .
                    "<option value=\"sg\" >Singapour</option>" .
                    "<option value=\"sk\" >Slovaquie</option>" .
                    "<option value=\"si\" >Slovénie</option>" .
                    "<option value=\"so\" >Somalie</option>" .
                    "<option value=\"sd\" >Soudan</option>" .
                    "<option value=\"sr\" >Suriname</option>" .
                    "<option value=\"sz\" >Swaziland</option>" .
                    "<option value=\"se\" >Suède</option>" .
                    "<option value=\"ch\" >Suisse</option>" .
                    "<option value=\"sy\" >Syrie</option>" .
                    "<option value=\"tw\" >Taïwan</option>" .
                    "<option value=\"tj\" >Tadjikistan</option>" .
                    "<option value=\"tz\" >Tanzanie</option>" .
                    "<option value=\"th\" >Thaïlande</option>" .
                    "<option value=\"tg\" >Togo</option>" .
                    "<option value=\"to\" >Tonga</option>" .
                    "<option value=\"tn\" >Tunisie</option>" .
                    "<option value=\"tr\" >Turquie</option>" .
                    "<option value=\"tm\" >Turkménistan</option>" .
                    "<option value=\"tv\" >Tuvalu</option>" .
                    "<option value=\"ug\" >Ouganda</option>" .
                    "<option value=\"ua\" >Ukraine</option>" .
                    "<option value=\"uy\" >Uruguay</option>" .
                    "<option value=\"uz\" >Ouzbékistan</option>" .
                    "<option value=\"vu\" >Vanuatu</option>" .
                    "<option value=\"va\" >Vatican</option>" .
                    "<option value=\"ve\" >Venezuela</option>" .
                    "<option value=\"vn\" >Vietnam</option>" .
                    "<option value=\"ye\" >Yémen</option>" .
                    "<option value=\"zm\" >Zambie</option>" .
                    "<option value=\"zw\" >Zimbabwe</option>" .
                    "<option value=\"rs\" >Serbie</option>" .
                    "<option value=\"me\" >Monténégro</option>";
					
						
$pays = array(
'af' => 'Afghanistan',
'al' => 'Albanie',
'dz' => 'Algérie',
'de' => 'Allemagne',
'ad' => 'Andorre',
'ao' => 'Angola',
'ai' => 'Anguilla',
'aq' => 'Antarctique',
'ar' => 'Argentine',
'am' => 'Arménie',
'aw' => 'Aruba',
'au' => 'Australie',
'at' => 'Autriche',
'az' => 'Azerbaïdjan',
'bs' => 'Bahamas',
'bh' => 'Bahreïn',
'bd' => 'Bangladesh',
'bb' => 'Barbade',
'by' => 'Biélorussie',
'be' => 'Belgique',
'bz' => 'Belize',
'bj' => 'Bénin',
'bm' => 'Bermudes',
'bt' => 'Bhoutan',
'bo' => 'Bolivie',
'ba' => 'Bosnie-Herzégovine',
'bw' => 'Botswana',
'br' => 'Brésil',
'bn' => 'Brunei',
'bg' => 'Bulgarie',
'bi' => 'Burundi',
'kh' => 'Cambodge',
'cm' => 'Cameroun',
'ca' => 'Canada',
'cv' => 'Cap Vert',
'cl' => 'Chili',
'cn' => 'Chine',
'co' => 'Colombie',
'km' => 'Comores',
'cr' => 'Costa Rica',
'hr' => 'Croatie',
'cu' => 'Cuba',
'cy' => 'Chypre',
'dk' => 'Danemark',
'dj' => 'Djibouti',
'dm' => 'Dominique',
'ec' => 'Équateur',
'eg' => 'Égypte',
'er' => 'Érythrée',
'es' => 'Espagne',
'ee' => 'Estonie',
'us' => 'Etats-Unis d\'Amérique',
'et' => 'Éthiopie',
'fk' => 'Îles Malouines',
'fo' => 'Îles Féroé',
'fj' => 'Fidji',
'fi' => 'Finlande',
'fr' => 'France',
'gf' => 'Guyane française',
'pf' => 'Polynésie française',
'ga' => 'Gabon',
'gm' => 'Gambie',
'ge' => 'Géorgie',
'gh' => 'Ghana',
'gi' => 'Gibraltar',
'gb' => 'Royaume-Uni',
'gr' => 'Grèce',
'gl' => 'Groenland',
'gd' => 'Grenade',
'gp' => 'Guadeloupe',
'gu' => 'Guam',
'gt' => 'Guatemala',
'gn' => 'Guinée',
'ht' => 'Haïti',
'hn' => 'Honduras',
'hu' => 'Hongrie',
'is' => 'Islande',
'in' => 'Inde',
'id' => 'Indonésie',
'ir' => 'Iran',
'iq' => 'Iraq',
'ie' => 'Irlande',
'il' => 'Israël',
'it' => 'Italie',
'ci' => 'Côte d\'Ivoire',
'jm' => 'Jamaïque',
'jp' => 'Japon',
'jo' => 'Jordanie',
'kz' => 'Kazakhstan',
'ke' => 'Kenya',
'ki' => 'Kiribati',
'kw' => 'Koweït',
'kg' => 'Kirghizstan',
'la' => 'Laos',
'lv' => 'Lettonie',
'lb' => 'Liban',
'ls' => 'Lesotho',
'lr' => 'Libéria',
'ly' => 'Libye',
'li' => 'Liechtenstein',
'lt' => 'Lituanie',
'lu' => 'Luxembourg',
'mo' => 'Macao',
'mk' => 'Macédoine',
'mg' => 'Madagascar',
'mw' => 'Malawi',
'my' => 'Malaisie',
'mv' => 'Maldives',
'ml' => 'Mali',
'mt' => 'Malte',
'mq' => 'Martinique',
'mr' => 'Mauritanie',
'mu' => 'Île Maurice',
'yt' => 'Mayotte',
'mx' => 'Mexique',
'md' => 'Moldavie',
'mc' => 'Monaco',
'mn' => 'Mongolie',
'ms' => 'Montserrat',
'ma' => 'Maroc',
'mz' => 'Mozambique',
'mm' => 'Myanmar',
'na' => 'Namibie',
'nr' => 'Nauru',
'np' => 'Népal',
'nl' => 'Pays-Bas',
'nc' => 'Nouvelle-Calédonie',
'nz' => 'Nouvelle-Zélande',
'ni' => 'Nicaragua',
'ne' => 'Niger',
'ng' => 'Nigeria',
'nu' => 'Nioué',
'kp' => 'Corée du Nord',
'no' => 'Norvège',
'om' => 'Oman',
'pk' => 'Pakistan',
'pw' => 'Palau',
'pa' => 'Panama',
'py' => 'Paraguay',
'pe' => 'Pérou',
'ph' => 'Philippines',
'pl' => 'Pologne',
'pt' => 'Portugal',
'pr' => 'Porto Rico',
'qa' => 'Qatar',
'cz' => 'République tchèque',
'cd' => 'République démocratique du Congo',
're' => 'Réunion',
'ro' => 'Roumanie',
'uk' => 'Royaume-Uni',
'ru' => 'Russie',
'rw' => 'Rwanda',
'ws' => 'Samoa',
'sm' => 'Saint-Marin',
'sn' => 'Sénégal',
'sc' => 'Seychelles',
'sl' => 'Sierra Leone',
'sg' => 'Singapour',
'sk' => 'Slovaquie',
'si' => 'Slovénie',
'so' => 'Somalie',
'sd' => 'Soudan',
'sr' => 'Suriname',
'sz' => 'Swaziland',
'se' => 'Suède',
'ch' => 'Suisse',
'sy' => 'Syrie',
'tw' => 'Taïwan',
'tj' => 'Tadjikistan',
'tz' => 'Tanzanie',
'th' => 'Thaïlande',
'tg' => 'Togo',
'to' => 'Tonga',
'tn' => 'Tunisie',
'tr' => 'Turquie',
'tm' => 'Turkménistan',
'tv' => 'Tuvalu',
'ug' => 'Ouganda',
'ua' => 'Ukraine',
'uy' => 'Uruguay',
'uz' => 'Ouzbékistan',
'vu' => 'Vanuatu',
'va' => 'Vatican',
've' => 'Venezuela',
'vn' => 'Vietnam',
'ye' => 'Yémen',
'zm' => 'Zambie',
'zw' => 'Zimbabwe',
'rs' => 'Serbie',
'me' => 'Monténégro'
);

$lang['circuits']['australie']['nom'] = "Australia";
$lang['circuits']['bahrein']['nom'] = "Bahreïn";
$lang['circuits']['malaisie']['nom'] = "Malaysia";
$lang['circuits']['chine']['nom'] = "China";
$lang['circuits']['espagne']['nom'] = "Spain";
$lang['circuits']['monaco']['nom'] = "Monaco";
$lang['circuits']['istanbul']['nom'] = "Istanbul";
$lang['circuits']['canada']['nom'] = "Canada";
$lang['circuits']['europe']['nom'] = "Europe";
$lang['circuits']['angleterre']['nom'] = "England";
$lang['circuits']['allemagne']['nom'] = "Germany";
$lang['circuits']['hongrie']['nom'] = "Hungary";
$lang['circuits']['belgique']['nom'] = "Belgium";
$lang['circuits']['italie']['nom'] = "Italy";
$lang['circuits']['singapour']['nom'] = "Singapore";
$lang['circuits']['japon']['nom'] = "Japan";
$lang['circuits']['coree']['nom'] = "Korea";
$lang['circuits']['bresil']['nom'] = "Brazil";
$lang['circuits']['abudhabi']['nom'] = "Abu Dhabi";
$lang['circuits']['inde']['nom'] = "India";


$lang['DE'] = "of";
$lang['DU'] = "du";
$lang['LE'] = "the";
$lang['LA'] = "la";
$lang['LES'] = "les";
$lang['AU'] = "au";
$lang['TOUR_P'] = "turn";
$lang['TOURS_P'] = "turns";
$lang['GAINS_SIEGE_SOCIAL'] = "Earnings of head office";
$lang['GAINS_STANDS'] = "Earnings from selling salls";
$lang['ET'] = "and";

$lang['SELECTIONNER'] = "Select";
$lang['JOUR'] = "day";
$lang['CARACTERISTIQUES'] = "Features";
$lang['ETAT_DE_SANTE'] = "Health";
$lang['ETAT_DE_FATIGUE'] = "Tiredness";
$lang['CONDITION_PHYSIQUE'] = "Fitness";
$lang['ENDURANCE'] = "Stamina";
$lang['CAP_APPRENTISSAGE'] = "Learning aptitude";
$lang['CHAUFFAGE_PNEUS'] = "Tyre warm up";
$lang['CONNAISSANCE_PISTE'] = "Track knowledge";
$lang['DEPARTS_ARRETES'] = "Starts";
$lang['DEPASSEMENTS'] = "Overtaking";
$lang['TEMPS_DE_REACTION'] = "Reaction time";
$lang['ARRETS_STANDS'] = "Pit stops";
$lang['MAJ'] = "Update";
$lang['PAR'] = "by";
$lang['A'] = "at";
$lang['COUT'] = "Cost";
$lang['FATIGUE'] = "Tiredness";
$lang['JOUEUR'] = "Player";
$lang['CLAN'] = "Clan";
$lang['HEURE'] = "Hour";
$lang['ECART'] = "Diff.";
$lang['POSITION'] = "Position";
$lang['TEMPS_TOTAL'] = "Total time";
$lang['MEILLEUR_TEMPS'] = "Best time";
$lang['POINTS'] = "Points";
$lang['DUREE'] = "Duration";
$lang['MODIFIER'] = "Change";
$lang['POINTS_P'] = "points";
$lang['ESSAIS'] = "Training";
$lang['QUALIFICATIONS'] = "Qualifications";
$lang['COURSE'] = "Race";
$lang['PAGE_PRECEDENTE'] = "Previous page";
$lang['PAGE_SUIVANTE'] = "Next page";
$lang['NOM'] = "Name";
$lang['LEGENDE'] = "Legend";
$lang['TDB'] = "Dashboard";
$lang['PAS_DE_PILOTES'] = "No drivers.";
$lang['CHERCHEUR_P'] = "researcher";
$lang['CHERCHEURS_P'] = "researchers";
$lang['PAS_DE_CHERCHEURS'] = "No researchers.";
$lang['PAS_DE_CLAN'] = "You have no clan.";
$lang['MON_COMPTE'] = "My Account";
$lang['PUBLICITE'] = "Publicity";
$lang['PILOTE_P'] = "driver";
$lang['PILOTES_P'] = "drivers";
$lang['FOOTER'] = "This website is optimized for Opera, Firefox and Google Chrome.";
$lang['COURSE_TERMINEE'] = "Race is over.";
$lang['COURSE_DANS'] = "Race in ";
$lang['JOUEURS'] = "Players";
$lang['JOUEUR'] = "Player";
$lang['JOUEUR_P'] = "player";
$lang['JOUEURS_P'] = "players";
$lang['EN_BON_ETAT'] = "in good condition";
$lang['ENDOMMAGEE'] = "in bad condition";
$lang['TRES_ENDOMMAGEE'] = "in very bad condition";
$lang['MESSAGERIE'] = "Messages";
$lang['FERMER'] = "Close";
$lang['CLIQUER_ICI_MARCHE'] = "Click here to go to the driver market";
$lang['ETES_VOUS_SUR'] = "Are you sure ?";

$lang['GESTION_PILOTES'] = "Driver management";
$lang['ETAT_VOITURE'] = "Car management";
$lang['GESTION_MOTEUR'] = "Engine management";
$lang['GESTION_TECH'] = "Engineers management";
$lang['GESTION_INFRA'] = "Infrastructure Management";
$lang['INFOS_CIRCUIT'] = "Race Track information";
$lang['NOM_UTILISATEUR'] = "Username";
$lang['MOT_DE_PASSE'] = "Password";
$lang['TOTAL_JOUEURS'] = "Total Players";
$lang['TOTAL_JOUEURS_ACTIFS'] = "Active Players";
$lang['TOTAL_PILOTES'] = "Total drivers";
$lang['TOTAL_NATIONS'] = "Nations represented";
$lang['DERNIERES_ACTUS_F1'] = "Latest F1 news with Fan-F1.com";
$lang['CONNECTES'] = "connected";
?>
