<?php
$lang['CONTENT_DESCRIPTION'] = "Jeu de gestion gratuit et multi-joueurs dans lequel vous incarnez le manager d'une écurie de Formule 1. Menez vos pilotes et leurs voitures à la victoire face à des centaines de joueurs venant des quatre coins de la planète.";
$lang['CONTENT_KEYWORDS'] = "F1, Formula One Manager, Formula 1, Formule 1, Formula 1 Game, Jeu Formule 1, Jeu, Jeu F1, Jeu de F1, Game, F1 Manager, FOM, Free Game, Formula One Game, Jeu Gratuit, Online, Web, Multijoueurs, Multiplayers, Simulation, Course F1, Jeu management, Racing, Racing Game";

$lang['BIENVENUE_SUR_FOM'] = "Bienvenue sur Formula One Manager !";
$lang['ACCUEIL'] = "Accueil";
$lang['INSCRIPTION'] = "Inscription";
$lang['NEWS'] = "News";
$lang['FORUMS'] = "Forums";
$lang['DOCUMENTATION'] = "Documentation";
$lang['CONNEXION'] = "Connexion";
$lang['DECONNEXION'] = "Déconnexion";
$lang['CONNEXION_AUTO'] = "Automatique";
$lang['PAS_INSCRIT'] = "Pas encore inscrit ?";
$lang['COMMUNAUTE'] = "Communauté";
$lang['STAFF'] = "L'Equipe";
$lang['SUPPORT'] = "Support";
$lang['MES_DONNEES'] = "Mes données";
$lang['PARTENAIRES'] = "Partenaires";
$lang['INSCRIVEZ_VOUS_GRATUITEMENT'] = "S'inscrire gratuitement";
$lang['CONNECTEZ_VOUS'] = "Se connecter";
$lang['PRESENTATION_DE_FOM'] = "Présentation de Formula One Manager";
$lang['ACCUEIL_FOM'] = "Accueil de FOM";
$lang['PILOTES'] = "Pilotes";
$lang['MEMBRES'] = "Membres";

$lang['TITRE'] = "Formula One Manager - Jeu Gratuit et Multijoueurs de F1";


$lang['PRESENTATION_FOM'] = "<p>Bienvenue sur Formula One Manager, le premier jeu de gestion de Formule 1 <strong>totalement gratuit</strong> et constamment mis-à-jour avec les dernières innovations du monde de la F1.</p>
<p>A la différence des autres jeux du même type, Formula One Manager est gratuit dans sa totalité. Aucune fonction ou amélioration ne peut être gagnée simplement en donnant de l'argent. Cela vous permettra de jouer tous ensemble avec les mêmes moyens pour réussir !</p>
<p>Pour vous inscrire, c'est <a href=\"/inscription/\">par ici</a> ! En quelques clics vous pourrez commencer à jouer, créer votre clan, manager votre pilote, gérer vos techniciens et vos dépenses (virtuelles, évidemment !), et plein d'autres choses encore.</p>
<p>Toute l'équipe de Formula One Manager vous souhaite un bon jeu. :-)</p>";

$lang['LISTE_DERNIERES_NEWS'] = "Liste des dernières nouveautés ";
$lang['LOGIN'] = "Login";

$lang['COMMENTER_CETTE_NEWS'] = "Commenter cette news";
$lang['COMMENTAIRE'] = "commentaire";
$lang['COMMENTAIRES'] = "commentaires";
$lang['NEWS_ECRITE_PAR'] = "Ecrite par";

$lang['PILOTE'] = "Pilote";
$lang['GARAGE']	= "Garage";
$lang['CIRCUIT'] = "Circuit";
$lang['FINANCES'] = "Finances";
$lang['STRUCTURES'] = "Structures";
$lang['MON_CLAN'] = "Mon clan";
$lang['CALENDRIER'] = "Calendrier";
$lang['CLASSEMENTS'] = "Classements";
$lang['HALL_OF_FAME'] = "Hall of Fame";
$lang['MON_COMPTE'] = "Mon compte";

$lang['A_DISPOSITION'] = "A disposition";
$lang['INFORMATIONS'] = "Informations";
$lang['CLASSEMENT'] = "Classement";
$lang['SEANCE'] = "Séance";
$lang['FIN_SEANCE_DANS'] = "Fin séance dans";
$lang['COURSE_DANS'] = "Course dans";
$lang['LA_COURSE'] = "La Course";

$lang['LISTE_PAYS'] = 	
					"<option value=\"fr\"   SELECTED  >France</option>" .
					"<option value=\"uk\" >Royaume-Uni</option>" .
					"<option value=\"de\" >Allemagne</option>" .
					"<option value=\"be\" >Belgique</option>" .
					"<option value=\"it\" >Italie</option>" .
					"<option value=\"es\" >Espagne</option>" .
					"<option value=\"us\" >Etats-Unis</option>" .
					"<option disabled>-----------------------</option>" .

					"<option value=\"af\" >Afghanistan</option>" .
                    "<option value=\"al\" >Albanie</option>" .
                    "<option value=\"dz\" >Algérie</option>" .
					"<option value=\"de\" >Allemagne</option>" .
                    "<option value=\"ad\" >Andorre</option>" .
                    "<option value=\"ao\" >Angola</option>" .
                    "<option value=\"ai\" >Anguilla</option>" .
                    "<option value=\"aq\" >Antarctique</option>" .
                    "<option value=\"ar\" >Argentine</option>" .
                    "<option value=\"am\" >Arménie</option>" .
                    "<option value=\"aw\" >Aruba</option>" .
                    "<option value=\"au\" >Australie</option>" .
                    "<option value=\"at\" >Autriche</option>" .
                    "<option value=\"az\" >Azerbaïdjan</option>" .
                    "<option value=\"bs\" >Bahamas</option>" .
                    "<option value=\"bh\" >Bahreïn</option>" .
                    "<option value=\"bd\" >Bangladesh</option>" .
                    "<option value=\"bb\" >Barbade</option>" .
                    "<option value=\"by\" >Biélorussie</option>" .
                    "<option value=\"be\" >Belgique</option>" .
                    "<option value=\"bz\" >Belize</option>" .
                    "<option value=\"bj\" >Bénin</option>" .
                    "<option value=\"bm\" >Bermudes</option>" .
                    "<option value=\"bt\" >Bhoutan</option>" .
                    "<option value=\"bo\" >Bolivie</option>" .
                    "<option value=\"ba\" >Bosnie-Herzégovine</option>" .
                    "<option value=\"bw\" >Botswana</option>" .
                    "<option value=\"br\" >Brésil</option>" .
                    "<option value=\"bn\" >Brunei</option>" .
                    "<option value=\"bg\" >Bulgarie</option>" .
                    "<option value=\"bi\" >Burundi</option>" .
                    "<option value=\"kh\" >Cambodge</option>" .
                    "<option value=\"cm\" >Cameroun</option>" .
                    "<option value=\"ca\" >Canada</option>" .
                    "<option value=\"cv\" >Cap Vert</option>" .
                    "<option value=\"cl\" >Chili</option>" .
                    "<option value=\"cn\" >Chine</option>" .
                    "<option value=\"co\" >Colombie</option>" .
                    "<option value=\"km\" >Comores</option>" .
                    "<option value=\"cr\" >Costa Rica</option>" .
                    "<option value=\"hr\" >Croatie</option>" .
                    "<option value=\"cu\" >Cuba</option>" .
                    "<option value=\"cy\" >Chypre</option>" .
                    "<option value=\"dk\" >Danemark</option>" .
                    "<option value=\"dj\" >Djibouti</option>" .
                    "<option value=\"dm\" >Dominique</option>" .
                    "<option value=\"ec\" >Équateur</option>" .
                    "<option value=\"eg\" >Égypte</option>" .
                    "<option value=\"er\" >Érythrée</option>" .
					"<option value=\"es\" >Espagne</option>" .
                    "<option value=\"ee\" >Estonie</option>" .
					"<option value=\"us\" >Etats-Unis d'Amérique</option>" .
                    "<option value=\"et\" >Éthiopie</option>" .
                    "<option value=\"fk\" >Îles Malouines</option>" .
                    "<option value=\"fo\" >Îles Féroé</option>" .
                    "<option value=\"fj\" >Fidji</option>" .
                    "<option value=\"fi\" >Finlande</option>" .
                    "<option value=\"fr\" >France</option>" .
                    "<option value=\"gf\" >Guyane française</option>" .
                    "<option value=\"pf\" >Polynésie française</option>" .
                    "<option value=\"ga\" >Gabon</option>" .
                    "<option value=\"gm\" >Gambie</option>" .
                    "<option value=\"ge\" >Géorgie</option>" .
                    "<option value=\"gh\" >Ghana</option>" .
                    "<option value=\"gi\" >Gibraltar</option>" .
                    "<option value=\"gr\" >Grèce</option>" .
                    "<option value=\"gl\" >Groenland</option>" .
                    "<option value=\"gd\" >Grenade</option>" .
                    "<option value=\"gp\" >Guadeloupe</option>" .
                    "<option value=\"gu\" >Guam</option>" .
                    "<option value=\"gt\" >Guatemala</option>" .
                    "<option value=\"gn\" >Guinée</option>" .
                    "<option value=\"ht\" >Haïti</option>" .
                    "<option value=\"hn\" >Honduras</option>" .
                    "<option value=\"hu\" >Hongrie</option>" .
                    "<option value=\"is\" >Islande</option>" .
                    "<option value=\"in\" >Inde</option>" .
                    "<option value=\"id\" >Indonésie</option>" .
                    "<option value=\"ir\" >Iran</option>" .
                    "<option value=\"iq\" >Iraq</option>" .
                    "<option value=\"ie\" >Irlande</option>" .
                    "<option value=\"il\" >Israël</option>" .
                    "<option value=\"it\" >Italie</option>" .
                    "<option value=\"ci\" >Côte d'Ivoire</option>" .
                    "<option value=\"jm\" >Jamaïque</option>" .
                    "<option value=\"jp\" >Japon</option>" .
                    "<option value=\"jo\" >Jordanie</option>" .
                    "<option value=\"kz\" >Kazakhstan</option>" .
                    "<option value=\"ke\" >Kenya</option>" .
                    "<option value=\"ki\" >Kiribati</option>" .
                    "<option value=\"kw\" >Koweït</option>" .
                    "<option value=\"kg\" >Kirghizstan</option>" .
                    "<option value=\"la\" >Laos</option>" .
                    "<option value=\"lv\" >Lettonie</option>" .
                    "<option value=\"lb\" >Liban</option>" .
                    "<option value=\"ls\" >Lesotho</option>" .
                    "<option value=\"lr\" >Libéria</option>" .
                    "<option value=\"ly\" >Libye</option>" .
                    "<option value=\"li\" >Liechtenstein</option>" .
                    "<option value=\"lt\" >Lituanie</option>" .
                    "<option value=\"lu\" >Luxembourg</option>" .
                    "<option value=\"mo\" >Macao</option>" .
                    "<option value=\"mk\" >Macédoine</option>" .
                    "<option value=\"mg\" >Madagascar</option>" .
                    "<option value=\"mw\" >Malawi</option>" .
                    "<option value=\"my\" >Malaisie</option>" .
                    "<option value=\"mv\" >Maldives</option>" .
                    "<option value=\"ml\" >Mali</option>" .
                    "<option value=\"mt\" >Malte</option>" .
                    "<option value=\"mq\" >Martinique</option>" .
                    "<option value=\"mr\" >Mauritanie</option>" .
                    "<option value=\"mu\" >Île Maurice</option>" .
                    "<option value=\"yt\" >Mayotte</option>" .
                    "<option value=\"mx\" >Mexique</option>" .
                    "<option value=\"md\" >Moldavie</option>" .
                    "<option value=\"mc\" >Monaco</option>" .
                    "<option value=\"mn\" >Mongolie</option>" .
                    "<option value=\"ms\" >Montserrat</option>" .
                    "<option value=\"ma\" >Maroc</option>" .
                    "<option value=\"mz\" >Mozambique</option>" .
                    "<option value=\"mm\" >Myanmar</option>" .
                    "<option value=\"na\" >Namibie</option>" .
                    "<option value=\"nr\" >Nauru</option>" .
                    "<option value=\"np\" >Népal</option>" .
                    "<option value=\"nl\" >Pays-Bas</option>" .
                    "<option value=\"nc\" >Nouvelle-Calédonie</option>" .
                    "<option value=\"nz\" >Nouvelle-Zélande</option>" .
                    "<option value=\"ni\" >Nicaragua</option>" .
                    "<option value=\"ne\" >Niger</option>" .
                    "<option value=\"ng\" >Nigeria</option>" .
                    "<option value=\"nu\" >Nioué</option>" .
                    "<option value=\"kp\" >Corée du Nord</option>" .
                    "<option value=\"no\" >Norvège</option>" .
                    "<option value=\"om\" >Oman</option>" .
                    "<option value=\"pk\" >Pakistan</option>" .
                    "<option value=\"pw\" >Palau</option>" .
                    "<option value=\"pa\" >Panama</option>" .
                    "<option value=\"py\" >Paraguay</option>" .
                    "<option value=\"pe\" >Pérou</option>" .
                    "<option value=\"ph\" >Philippines</option>" .
                    "<option value=\"pl\" >Pologne</option>" .
                    "<option value=\"pt\" >Portugal</option>" .
                    "<option value=\"pr\" >Porto Rico</option>" .
                    "<option value=\"qa\" >Qatar</option>" .
					"<option value=\"cz\" >République tchèque</option>" .
                    "<option value=\"cd\" >Rép. dém. du Congo</option>" .
                    "<option value=\"re\" >Réunion</option>" .
                    "<option value=\"ro\" >Roumanie</option>" .
					"<option value=\"uk\" >Royaume-Uni</option>" .
                    "<option value=\"ru\" >Russie</option>" .
                    "<option value=\"rw\" >Rwanda</option>" .
                    "<option value=\"ws\" >Samoa</option>" .
                    "<option value=\"sm\" >Saint-Marin</option>" .
                    "<option value=\"sn\" >Sénégal</option>" .
                    "<option value=\"sc\" >Seychelles</option>" .
                    "<option value=\"sl\" >Sierra Leone</option>" .
                    "<option value=\"sg\" >Singapour</option>" .
                    "<option value=\"sk\" >Slovaquie</option>" .
                    "<option value=\"si\" >Slovénie</option>" .
                    "<option value=\"so\" >Somalie</option>" .
                    "<option value=\"sd\" >Soudan</option>" .
                    "<option value=\"sr\" >Suriname</option>" .
                    "<option value=\"sz\" >Swaziland</option>" .
                    "<option value=\"se\" >Suède</option>" .
                    "<option value=\"ch\" >Suisse</option>" .
                    "<option value=\"sy\" >Syrie</option>" .
                    "<option value=\"tw\" >Taïwan</option>" .
                    "<option value=\"tj\" >Tadjikistan</option>" .
                    "<option value=\"tz\" >Tanzanie</option>" .
                    "<option value=\"th\" >Thaïlande</option>" .
                    "<option value=\"tg\" >Togo</option>" .
                    "<option value=\"to\" >Tonga</option>" .
                    "<option value=\"tn\" >Tunisie</option>" .
                    "<option value=\"tr\" >Turquie</option>" .
                    "<option value=\"tm\" >Turkménistan</option>" .
                    "<option value=\"tv\" >Tuvalu</option>" .
                    "<option value=\"ug\" >Ouganda</option>" .
                    "<option value=\"ua\" >Ukraine</option>" .
                    "<option value=\"uy\" >Uruguay</option>" .
                    "<option value=\"uz\" >Ouzbékistan</option>" .
                    "<option value=\"vu\" >Vanuatu</option>" .
                    "<option value=\"va\" >Vatican</option>" .
                    "<option value=\"ve\" >Venezuela</option>" .
                    "<option value=\"vn\" >Vietnam</option>" .
                    "<option value=\"ye\" >Yémen</option>" .
                    "<option value=\"zm\" >Zambie</option>" .
                    "<option value=\"zw\" >Zimbabwe</option>" .
                    "<option value=\"rs\" >Serbie</option>" .
                    "<option value=\"me\" >Monténégro</option>";
					
						
$pays = array(
'af' => 'Afghanistan',
'al' => 'Albanie',
'dz' => 'Algérie',
'de' => 'Allemagne',
'ad' => 'Andorre',
'ao' => 'Angola',
'ai' => 'Anguilla',
'aq' => 'Antarctique',
'ar' => 'Argentine',
'am' => 'Arménie',
'aw' => 'Aruba',
'au' => 'Australie',
'at' => 'Autriche',
'az' => 'Azerbaïdjan',
'bs' => 'Bahamas',
'bh' => 'Bahreïn',
'bd' => 'Bangladesh',
'bb' => 'Barbade',
'by' => 'Biélorussie',
'be' => 'Belgique',
'bz' => 'Belize',
'bj' => 'Bénin',
'bm' => 'Bermudes',
'bt' => 'Bhoutan',
'bo' => 'Bolivie',
'ba' => 'Bosnie-Herzégovine',
'bw' => 'Botswana',
'br' => 'Brésil',
'bn' => 'Brunei',
'bg' => 'Bulgarie',
'bi' => 'Burundi',
'kh' => 'Cambodge',
'cm' => 'Cameroun',
'ca' => 'Canada',
'cv' => 'Cap Vert',
'cl' => 'Chili',
'cn' => 'Chine',
'co' => 'Colombie',
'km' => 'Comores',
'cr' => 'Costa Rica',
'hr' => 'Croatie',
'cu' => 'Cuba',
'cy' => 'Chypre',
'dk' => 'Danemark',
'dj' => 'Djibouti',
'dm' => 'Dominique',
'ec' => 'Équateur',
'eg' => 'Égypte',
'er' => 'Érythrée',
'es' => 'Espagne',
'ee' => 'Estonie',
'us' => 'Etats-Unis d\'Amérique',
'et' => 'Éthiopie',
'fk' => 'Îles Malouines',
'fo' => 'Îles Féroé',
'fj' => 'Fidji',
'fi' => 'Finlande',
'fr' => 'France',
'gf' => 'Guyane française',
'pf' => 'Polynésie française',
'ga' => 'Gabon',
'gm' => 'Gambie',
'ge' => 'Géorgie',
'gh' => 'Ghana',
'gi' => 'Gibraltar',
'gb' => 'Royaume-Uni',
'gr' => 'Grèce',
'gl' => 'Groenland',
'gd' => 'Grenade',
'gp' => 'Guadeloupe',
'gu' => 'Guam',
'gt' => 'Guatemala',
'gn' => 'Guinée',
'ht' => 'Haïti',
'hn' => 'Honduras',
'hu' => 'Hongrie',
'is' => 'Islande',
'in' => 'Inde',
'id' => 'Indonésie',
'ir' => 'Iran',
'iq' => 'Iraq',
'ie' => 'Irlande',
'il' => 'Israël',
'it' => 'Italie',
'ci' => 'Côte d\'Ivoire',
'jm' => 'Jamaïque',
'jp' => 'Japon',
'jo' => 'Jordanie',
'kz' => 'Kazakhstan',
'ke' => 'Kenya',
'ki' => 'Kiribati',
'kw' => 'Koweït',
'kg' => 'Kirghizstan',
'la' => 'Laos',
'lv' => 'Lettonie',
'lb' => 'Liban',
'ls' => 'Lesotho',
'lr' => 'Libéria',
'ly' => 'Libye',
'li' => 'Liechtenstein',
'lt' => 'Lituanie',
'lu' => 'Luxembourg',
'mo' => 'Macao',
'mk' => 'Macédoine',
'mg' => 'Madagascar',
'mw' => 'Malawi',
'my' => 'Malaisie',
'mv' => 'Maldives',
'ml' => 'Mali',
'mt' => 'Malte',
'mq' => 'Martinique',
'mr' => 'Mauritanie',
'mu' => 'Île Maurice',
'yt' => 'Mayotte',
'mx' => 'Mexique',
'md' => 'Moldavie',
'mc' => 'Monaco',
'mn' => 'Mongolie',
'ms' => 'Montserrat',
'ma' => 'Maroc',
'mz' => 'Mozambique',
'mm' => 'Myanmar',
'na' => 'Namibie',
'nr' => 'Nauru',
'np' => 'Népal',
'nl' => 'Pays-Bas',
'nc' => 'Nouvelle-Calédonie',
'nz' => 'Nouvelle-Zélande',
'ni' => 'Nicaragua',
'ne' => 'Niger',
'ng' => 'Nigeria',
'nu' => 'Nioué',
'kp' => 'Corée du Nord',
'no' => 'Norvège',
'om' => 'Oman',
'pk' => 'Pakistan',
'pw' => 'Palau',
'pa' => 'Panama',
'py' => 'Paraguay',
'pe' => 'Pérou',
'ph' => 'Philippines',
'pl' => 'Pologne',
'pt' => 'Portugal',
'pr' => 'Porto Rico',
'qa' => 'Qatar',
'cz' => 'République tchèque',
'cd' => 'République démocratique du Congo',
're' => 'Réunion',
'ro' => 'Roumanie',
'uk' => 'Royaume-Uni',
'ru' => 'Russie',
'rw' => 'Rwanda',
'ws' => 'Samoa',
'sm' => 'Saint-Marin',
'sn' => 'Sénégal',
'sc' => 'Seychelles',
'sl' => 'Sierra Leone',
'sg' => 'Singapour',
'sk' => 'Slovaquie',
'si' => 'Slovénie',
'so' => 'Somalie',
'sd' => 'Soudan',
'sr' => 'Suriname',
'sz' => 'Swaziland',
'se' => 'Suède',
'ch' => 'Suisse',
'sy' => 'Syrie',
'tw' => 'Taïwan',
'tj' => 'Tadjikistan',
'tz' => 'Tanzanie',
'th' => 'Thaïlande',
'tg' => 'Togo',
'to' => 'Tonga',
'tn' => 'Tunisie',
'tr' => 'Turquie',
'tm' => 'Turkménistan',
'tv' => 'Tuvalu',
'ug' => 'Ouganda',
'ua' => 'Ukraine',
'uy' => 'Uruguay',
'uz' => 'Ouzbékistan',
'vu' => 'Vanuatu',
'va' => 'Vatican',
've' => 'Venezuela',
'vn' => 'Vietnam',
'ye' => 'Yémen',
'zm' => 'Zambie',
'zw' => 'Zimbabwe',
'rs' => 'Serbie',
'me' => 'Monténégro'
);

$lang['circuits']['australie']['nom'] = "Australie";
$lang['circuits']['bahrein']['nom'] = "Bahreïn";
$lang['circuits']['malaisie']['nom'] = "Malaisie";
$lang['circuits']['chine']['nom'] = "Chine";
$lang['circuits']['espagne']['nom'] = "Espagne";
$lang['circuits']['monaco']['nom'] = "Monaco";
$lang['circuits']['istanbul']['nom'] = "Istanbul";
$lang['circuits']['canada']['nom'] = "Canada";
$lang['circuits']['europe']['nom'] = "Europe";
$lang['circuits']['angleterre']['nom'] = "Angleterre";
$lang['circuits']['allemagne']['nom'] = "Allemagne";
$lang['circuits']['hongrie']['nom'] = "Hongrie";
$lang['circuits']['belgique']['nom'] = "Belgique";
$lang['circuits']['italie']['nom'] = "Italie";
$lang['circuits']['singapour']['nom'] = "Singapour";
$lang['circuits']['japon']['nom'] = "Japon";
$lang['circuits']['coree']['nom'] = "Corée";
$lang['circuits']['bresil']['nom'] = "Brésil";
$lang['circuits']['abudhabi']['nom'] = "Abu Dhabi";
$lang['circuits']['inde']['nom'] = "Inde";


$lang['DE'] = "de";
$lang['DU'] = "du";
$lang['LE'] = "le";
$lang['LA'] = "la";
$lang['LES'] = "les";
$lang['AU'] = "au";
$lang['TOUR_P'] = "tour";
$lang['TOURS_P'] = "tours";
$lang['GAINS_SIEGE_SOCIAL'] = "Gains siège social";
$lang['GAINS_STANDS'] = "Gains stands de vente";
$lang['ET'] = "et";

$lang['SELECTIONNER'] = "Sélectionner";
$lang['JOUR'] = "jour";
$lang['CARACTERISTIQUES'] = "Caractéristiques";
$lang['ETAT_DE_SANTE'] = "Etat de santé";
$lang['ETAT_DE_FATIGUE'] = "Etat de fatigue";
$lang['CONDITION_PHYSIQUE'] = "Cond. Phys.";
$lang['ENDURANCE'] = "Endurance";
$lang['CAP_APPRENTISSAGE'] = "Cap. Apprentissage";
$lang['CHAUFFAGE_PNEUS'] = "Chauffage pneus";
$lang['CONNAISSANCE_PISTE'] = "Connaissance piste";
$lang['DEPARTS_ARRETES'] = "Départs arrêtés";
$lang['DEPASSEMENTS'] = "Dépassements";
$lang['TEMPS_DE_REACTION'] = "Temps de réaction";
$lang['ARRETS_STANDS'] = "Arrêts aux stands";
$lang['MAJ'] = "Mettre à jour";
$lang['PAR'] = "par";
$lang['A'] = "à";
$lang['COUT'] = "Coût";
$lang['FATIGUE'] = "Fatigue";
$lang['JOUEUR'] = "Joueur";
$lang['CLAN'] = "Clan";
$lang['HEURE'] = "Heure";
$lang['ECART'] = "Ecart";
$lang['POSITION'] = "Position";
$lang['TEMPS_TOTAL'] = "Temps total";
$lang['MEILLEUR_TEMPS'] = "Meilleur temps";
$lang['POINTS'] = "Points";
$lang['DUREE'] = "Durée";
$lang['MODIFIER'] = "Modifier";
$lang['POINTS_P'] = "points";
$lang['ESSAIS'] = "Essais";
$lang['QUALIFICATIONS'] = "Qualifications";
$lang['COURSE'] = "Course";
$lang['PAGE_PRECEDENTE'] = "Page précédente";
$lang['PAGE_SUIVANTE'] = "Page suivante";
$lang['NOM'] = "Nom";
$lang['LEGENDE'] = "Légende";
$lang['TDB'] = "Tableau de Bord";
$lang['PAS_DE_PILOTES'] = "Pas de pilotes.";
$lang['CHERCHEUR_P'] = "chercheur";
$lang['CHERCHEURS_P'] = "chercheurs";
$lang['PAS_DE_CHERCHEURS'] = "Pas de chercheurs.";
$lang['PAS_DE_CLAN'] = "Vous n'avez pas de clan.";
$lang['MON_COMPTE'] = "Mon Compte";
$lang['PUBLICITE'] = "Publicité";
$lang['PILOTE_P'] = "pilote";
$lang['PILOTES_P'] = "pilotes";
$lang['FOOTER'] = "Ce site est optimisé pour Opera, Firefox et Google Chrome.";
$lang['COURSE_TERMINEE'] = "Course terminée.";
$lang['COURSE_DANS'] = "Course dans ";
$lang['JOUEURS'] = "Joueurs";
$lang['JOUEUR'] = "Joueur";
$lang['JOUEUR_P'] = "joueur";
$lang['JOUEURS_P'] = "joueurs";
$lang['EN_BON_ETAT'] = "en bon état";
$lang['ENDOMMAGEE'] = "endommagée";
$lang['TRES_ENDOMMAGEE'] = "très endommagée";
$lang['MESSAGERIE']	= "Messagerie";
$lang['FERMER'] = "Fermer";
$lang['CLIQUER_ICI_MARCHE'] = "Cliquez ici pour accéder au marché des pilotes";
$lang['ETES_VOUS_SUR'] = "Etes-vous sûr ?";

$lang['GESTION_PILOTES'] = "Gestion des pilotes";
$lang['ETAT_VOITURE'] = "Etat de la voiture";
$lang['GESTION_MOTEUR'] = "Gestion du moteur";
$lang['GESTION_TECH'] = "Gestion des techniciens";
$lang['GESTION_INFRA'] = "Gestion des infrastructures";
$lang['INFOS_CIRCUIT'] = "Informations du circuit en cours";
$lang['NOM_UTILISATEUR'] = "Nom d'utilisateur";
$lang['MOT_DE_PASSE'] = "Mot de passe";
$lang['TOTAL_JOUEURS'] = "Total des joueurs";
$lang['TOTAL_JOUEURS_ACTIFS'] = "Joueurs actifs";
$lang['TOTAL_PILOTES'] = "Total des pilotes";
$lang['TOTAL_NATIONS'] = "Nations représentées";
$lang['DERNIERES_ACTUS_F1'] = "Dernières actualités de la F1 avec Fan-F1.com";
$lang['CONNECTES'] = "connectés";
?>
